site_name: Uberon multi-species anatomy ontology
theme: readthedocs
nav:
  - Home: index.md
  - About:
      - About Uberon: about.md
      - The Uberon team: team.md
      - Uberon on GitHub: https://github.com/obophenotype/uberon
      - Issue Tracker: https://github.com/obophenotype/uberon
      - Adopters: adopters.md
      - Acknowledgements: acknowledgements.md
      - Cite: cite.md
  - Browse:
      - OLS: https://www.ebi.ac.uk/ols/ontologies/uberon
      - Ontobee: http://www.ontobee.org/ontology/UBERON
      - BioPortal: https://bioportal.bioontology.org/ontologies/UBERON
      - Bgee Anatomical Homology: https://bgee.org/?page=anat_similarities
  - Download:
      - Current release: current_release.md
      - Cross-species bridge files: bridges.md
      - Combined Multispecies Ontologies: combined_multispecies.md
      - Releases before 2020: old_releases.md
  - How-to guides:
      - How to contribute to Uberon: contributing.md
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md
  - Ubeorn Internal Docs: 
      - Uberon Release: uberon-release.md
  - Reference:
      - Wiki: https://github.com/obophenotype/uberon/wiki
      - Uberon Manual: https://github.com/obophenotype/uberon/wiki/Manual
      - User Documentation: https://github.com/obophenotype/uberon/wiki/Manual#user-docs
      - Editors documentation: https://github.com/obophenotype/uberon/wiki/Manual#editor-docs
      - Design Patterns: https://github.com/obophenotype/uberon/wiki/Manual#design-patterns
      - Anatomical Structures: https://github.com/obophenotype/uberon/wiki/Manual#anatomical-structures
      - Uberon Build Pipeline: uberon_build_pipeline.md

